version: '3.2'

services:
  influxdb:
    image: influxdb:latest
    volumes:
      - "/data/global/influxdb/conf:/etc/influxdb"
      - "/data/global/influxdb/data:/var/lib/influxdb"      
    networks:
      - telemetry-net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - node.role==manager
  telegraf1:
    image: telegraf:latest
    environment:
      - AGENT_NAME=rpi-node01
      - HOST_ETC=/rootfs/etc
      - HOST_SYS=/rootfs/sys
      - HOST_PROC=/rootfs/proc
    volumes:
      - "/data/global/telegraf:/etc/telegraf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/:/rootfs:ro"
    networks:
      - telemetry-net
    deploy:
      mode: global
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - node.hostname==rpi-node01
  telegraf2:
    image: telegraf:latest
    environment:
      - AGENT_NAME=rpi-node02
      - HOST_ETC=/rootfs/etc
      - HOST_SYS=/rootfs/sys
      - HOST_PROC=/rootfs/proc      
    volumes:
      - "/data/global/telegraf:/etc/telegraf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/:/rootfs:ro"
    networks:
      - telemetry-net
    deploy:
      mode: global
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - node.hostname==rpi-node02
  telegraf3:
    image: telegraf:latest
    environment:
      - AGENT_NAME=rpi-node03
      - HOST_ETC=/rootfs/etc
      - HOST_SYS=/rootfs/sys
      - HOST_PROC=/rootfs/proc      
    volumes:
      - "/data/global/telegraf:/etc/telegraf"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/:/rootfs:ro"
    networks:
      - telemetry-net
    deploy:
      mode: global
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - node.hostname==rpi-node03
  grafana:
    image: joseba/rpi-grafana:latest
    volumes:
      - "/data/global/grafana/data:/var/lib/grafana"
      - "/data/global/grafana/conf:/etc/grafana"
    networks:
      - proxy-net
      - telemetry-net
    deploy:
      replicas: 1
      labels:
        - "traefik.port=3000"
        - "traefik.backend=grafana"
        - "traefik.frontend.rule=Host:grafana.joseba.io"
      placement:
        constraints:
          - node.role==manager          
networks:
  proxy-net:
    driver: overlay
    external: true
  telemetry-net:
    driver: overlay
    external: true

